<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AplicacionqueGestionaUnaBiblioteca.BL\AplicacionqueGestionaUnaBiblioteca.BL.csproj" />
    <ProjectReference Include="..\AplicacionqueGestionaUnaBiblioteca.Model\AplicacionqueGestionaUnaBiblioteca.Model.csproj" />
  </ItemGroup>

</Project>
